name: teamang_hackathon
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.0
  animated_login: ^1.5.1
  flutter_login: ^3.1.0
  curved_navigation_bar: ^1.0.3
  maps_launcher: ^2.0.1
  google_maps_flutter: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5shirt.png
    - assets/images/01profile.png
    - assets/images/logo.png
